version: '3.8'

services:
  web:

    # to build the image defined in DockerFile
    build: .

    # rememder we have to run the command in the container that's why /code/manage.py & 0.0.0.0 represents accept any IP address
    # this will only run when you run the image. - CMD -
    command: python /code/manage.py runserver 0.0.0.0:8000

    volumes: 
    # Obvoiusly we do not want that changes happens only in the container but also in the actual project (host machine).
    # this is { BIND MOUNTS } example
      - .:/code
    
    ports:
      - 8000:8000

    depends_on:
    # our app can't run without database.
      - db


  db:
    image: postgres

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes: 
      # where our database will be managed by the docker compose

      #  ' /var/lib/postgresql/data ' this is where postgresql stores it's data
      # postgres_data is a volume shared across all containers, helps to persist the data even if you removed any container
      #  we not intend to link to the actual project just to keep things simple.
      - postgres_data:/var/lib/postgresql/data

  
volumes: 
  postgres_data: